name: Issue to Project
on:
  issues:
    types: [opened, labeled]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        id: addItem
        with:
          project-url: https://github.com/orgs/OpenPecha/projects/88/
          github-token: ${{ secrets.GH_PAT }}
          labeled: bug, Feedback
          label-operator: OR
      - name: Debug output itemId
        run: echo "Item ID is ${{ steps.addItem.outputs.itemId }}"