name: Sync Issues to Project

on:
  issues:
    types: [opened, edited]

jobs:
  sync_to_project:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Sync issue to project
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        ISSUE_URL=$(jq -r .issue.url $GITHUB_EVENT_PATH)
        PROJECT_ID="88"
        PROJECT_VIEW_ID="7"
        PROJECT_URL="https://api.github.com/projects/$PROJECT_ID/views/$PROJECT_VIEW_ID/items"
        
        curl -X POST -H "Authorization: token $GH_PAT" -H "Accept: application/vnd.github.v3+json" $PROJECT_URL -d "{\"content_id\": $(jq -r .issue.id $GITHUB_EVENT_PATH), \"content_type\": \"Issue\"}"
